const firebaseConfig={apiKey:"AIzaSyAhN2a4m6PkTwFOvJ88TreD1lCERYJD7m0",authDomain:"kostory-db.firebaseapp.com",databaseURL:"https://kostory-db-default-rtdb.asia-southeast1.firebasedatabase.app",projectId:"kostory-db",storageBucket:"kostory-db.appspot.com",messagingSenderId:"447318101438",appId:"1:447318101438:web:7aba8e16ccee69fd3c53def"};
firebase.initializeApp(firebaseConfig);const db=firebase.database();

const kosts={"Kostory Mekar":["101","102","103","105","106","107","108","201","202","203","205","206","207","208"],"Kostory Satria":["101","102","103","105","106","107","108","109","201","202","203","205","206","207","208","209","210"],"Kostory Mitra":["101","102","103","105","106","107","108","109","110","112","201","202","203","205","206","207"],"Ecokost by Kostory":["101","102","103","105","106","107","108","109","110","111","112","115","116","117","118","119","120","121","122","126"],"Mitraya by Kostory":["100","101","102","103","105","106","107","108","201","202","203","205","206","207","208","209","210","211","212"],"Inaya Bukit by Kostory":["101","102","103","105","201","202","203","205"]};
const hakAkses={"admin":"all","mekar":"Kostory Mekar","satria":"Kostory Satria","mitra":"Kostory Mitra","ecokost":"Ecokost by Kostory","mitraya":"Mitraya by Kostory","inaya":"Inaya Bukit by Kostory"};
const passwordDb={"admin":"ramenuno20","mekar":"kopipait69","satria":"cilukba123","mitra":"ayamgeprek77","ecokost":"mirebus08","mitraya":"odading88","inaya":"nasiuduk21"};

let currentUser=null,allowedKosts=[],currentKost=null,currentRoom=null,currentData=null;

window.onload=()=>{const s=localStorage.getItem("kostoryUser");if(s&&passwordDb[s]){currentUser=s;allowedKosts=hakAkses[s]==="all"?Object.keys(kosts):[hakAkses[s]];document.getElementById("loginScreen").classList.add("hidden");document.getElement+%

"app").classList.remove("hidden");loadDashboard();}};
function logout(){localStorage.removeItem("kostoryUser");location.reload();}
window.login=()=>{const u=document.getElementById("username").value.trim().toLowerCase(),p=document.getElementById("password").value;if(passwordDb[u]&&passwordDb[u]===p){currentUser=u;localStorage.setItem("kostoryUser",u);allowedKosts=hakAkses[u]==="all"?Object.keys(kosts):[hakAkses[u]];document.getElementById("loginScreen").classList.add("hidden");document.getElementById("app").classList.remove("hidden");loadDashboard();}else alert("Salah bro!");};

const formatDate=d=>!d?"-":`${new Date(d).getDate()} ${new Date(d).toLocaleDateString("id-ID",{month:"short"}).replace(".","")} ${new Date(d).getFullYear().toString().slice(-2)}`;
const hitungLamaTinggal=(m,k=new Date())=>{const diff=Math.floor((new Date(k)-new Date(m))/86400000);return `${Math.floor(diff/365)}y ${Math.floor((diff%365)/30)}bln ${diff%30}h`};
const closeModal=()=>document.querySelectorAll(".modal").forEach(m=>m.classList.add("hidden"));
const backToDashboard=()=>{["penghuniListPage","checkoutListPage","checkinListPage"].forEach(id=>document.getElementById(id)?.classList.add("hidden"));document.getElementById("app").classList.remove("hidden");};

function loadDashboard(){const c=document.getElementById("kostList");c.innerHTML="<div style='text-align:center;padding:100px;color:#666'>Loading...</div>";document.getElementById("totalStats").innerHTML="Memuat...";let tot=0,isi=0;allowedKosts.forEach(n=>{tot+=kosts[n].length;const card=document.createElement("div");card.className="kost-card";card.innerHTML=`<h2 style="color:#1e40af;margin-bottom:20px">${n}</h2><div class="room-grid"></div>`;c.appendChild(card);const g=card.querySelector(".room-grid");kosts[n].forEach(r=>{db.ref(`kosts/${n}/${r}`).once("value").then(s=>{const d=s.val();const b=document.createElement("div");b.className="room";b.onclick=()=>openModal(n,r);if(!d||!d.nama||!d.checkout){b.classList.add("kosong");b.innerHTML=r+"<br><small>Kosong</small>";}else{isi++;b.classList.add(d.status||"staying");b.innerHTML=r+"<br><small>"+d.nama+"</small>";}g.appendChild(b);document.getElementById("totalStats").innerHTML=`Total Kamar: ${tot} | Terisi: ${isi} (${Math.round(isi/tot*100)}%)`;});});});}

window.openModal=(kost,room,fromCO=false)=>{currentKost=kost;currentRoom=room;const ref=fromCO?db.ref(`checkout/${kost}/${room}`):db.ref(`kosts/${kost}/${room}`);ref.once("value").then(s=>{currentData=s.val()||{};document.getElementById("detailModal").classList.remove("hidden");document.getElementById("modalTitle").textContent=currentData.nama?`EDIT ${room} - ${currentData.nama}`:`CHECK-IN ${room}`;["nama","hp","alamat","perusahaan","tanggalLahir","jenis","durasi","kendaraan","harga","deposit","tanggal","tokenAwal","tokenAkhirCheckout","noRek","namaBank","namaRekening","catatan","namaKeluarga","hubunganKeluarga","hpKeluarga"].forEach(f=>document.getElementById(f).value=currentData[f]||"");document.getElementById("statusPenghuni").value=currentData.status||"staying";document.getElementById("tanggal").value=currentData.tanggalMasuk||new Date().toISOString().split("T")[0];const b=document.getElementById("modalButtons");b.innerHTML=`<button class="btn-danger" onclick="closeModal()">Batal</button><button class="btn-success full" onclick="simpanData()">${currentData.nama?"UPDATE":"CHECK-IN"}</button>`;if(currentData.nama&&!currentData.checkout){b.innerHTML+=`<button class="btn-wa" onclick="kirimWA()">WA</button><button class="btn-danger" onclick="checkoutModal()">CHECK-OUT</button><button class="tagih-btn" onclick="tagihModal()">TAGIH</button><button class="lunas-btn" onclick="lunasModal()">LUNAS</button>`;}});};

window.simpanData=()=>{const data={status:document.getElementById("statusPenghuni").value,nama:document.getElementById("nama").value.trim(),hp:document.getElementById("hp").value.trim(),alamat:document.getElementById("alamat").value,perusahaan:document.getElementById("perusahaan").value,tanggalLahir:document.getElementById("tanggalLahir").value,jenis:document.getElementById("jenis").value,durasi:document.getElementById("durasi").value,kendaraan:document.getElementById("kendaraan").value,harga:Number(document.getElementById("harga").value)||0,deposit:Number(document.getElementById("deposit").value)||0,tanggalMasuk:document.getElementById("tanggal").value,tokenAwal:Number(document.getElementById("tokenAwal").value)||0,noRek:document.getElementById("noRek").value,namaBank:document.getElementById("namaBank").value,namaRekening:document.getElementById("namaRekening").value,catatan:document.getElementById("catatan").value,namaKeluarga:document.getElementById("namaKeluarga").value,hubunganKeluarga:document.getElementById("hubunganKeluarga").value,hpKeluarga:document.getElementById("hpKeluarga").value};if(!data.nama||!data.hp)return alert("Nama & HP wajib!");db.ref(`kosts/${currentKost}/${currentRoom}`).set(data).then(()=>{closeModal();alert("Tersimpan!");loadDashboard();});};

window.checkoutModal=()=>{closeModal();document.getElementById("checkoutModal").classList.remove("hidden");document.getElementById("coNama").textContent=currentData.nama;document.getElementById("coKamar").textContent=currentRoom;document.getElementById("tanggalCheckout").value=new Date().toISOString().split("T")[0];};
window.prosesCheckout=()=>{const t=document.getElementById("tanggalCheckout").value,k=Number(document.getElementById("tokenAkhir").value)||0;if(!t)return alert("Isi tanggal!");const f={...currentData,checkout:true,tanggalCheckout:t,tokenAkhir:k,selisihToken:k-(currentData.tokenAwal||0)};db.ref(`checkout/${currentKost}/${currentRoom}`).set(f).then(()=>db.ref(`kosts/${currentKost}/${currentRoom}`).remove().then(()=>{closeModal();alert("Check-out sukses!");loadDashboard();}));};

window.tagihModal=()=>{closeModal();document.getElementById("tagihModal").classList.remove("hidden");document.getElementById("jatuhTempo").value=new Date().toISOString().split("T")[0];document.getElementById("nominalTagihan").value=currentData.harga||"";};
window.kirimTagihan=()=>{const t=document.getElementById("jatuhTempo").value,n=document.getElementById("nominalTagihan").value;window.open(`https://wa.me/${currentData.hp}?text=${encodeURIComponent(`*TAGIHAN KOST*\n\n${currentData.nama}\nKamar ${currentRoom}\n\nRp ${Number(n).toLocaleString("id-ID")}\nJatuh Tempo: ${formatDate(t)}\n\nTransfer ke:\n${currentData.noRek||"-"} a/n ${currentData.namaRekening||"-"} (${currentData.namaBank||"-"})`)}`);closeModal();};
window.lunasModal=()=>{closeModal();document.getElementById("lunasModal").classList.remove("hidden");document.getElementById("tanggalBayar").value=new Date().toISOString().split("T")[0];document.getElementById("jumlahBayar").value=currentData.harga||"";};
window.catatLunas=()=>{const t=document.getElementById("tanggalBayar").value,j=document.getElementById("jumlahBayar").value;db.ref(`kosts/${currentKost}/${currentRoom}`).update({lunas:true,tanggalLunas:t,jumlahLunas:Number(j)}).then(()=>{closeModal();alert("Lunas!");loadDashboard();});};

window.showPenghuniList=async()=>{document.getElementById("app").classList.add("hidden");document.getElementById("penghuniListPage").classList.remove("hidden");const l=[];for(const k of allowedKosts)for(const r of kosts[k]){const s=await db.ref(`kosts/${k}/${r}`).once("value");const d=s.val();if(d?.nama&&!d.checkout)l.push({room:r,d});}document.getElementById("penghuniListContainer").innerHTML=l.map(p=>`<div class="penghuni-item" onclick="openModal('${p.d.kost||allowedKosts[0]}','${p.room}')"><div><strong>${p.room} - ${p.d.nama}</strong><br><small>${p.d.hp} • ${p.d.durasi} • ${hitungLamaTinggal(p.d.tanggalMasuk)}</small></div>${p.d.lunas?'<span class="status-lunas">LUNAS</span>':'<span style="background:#fee2e2;color:#b91c1c;padding:6px 12px;border-radius:8px">BELUM</span>'}</div>`).join("")||"Belum ada penghuni";};

window.showCheckoutList=async()=>{document.getElementById("app").classList.add("hidden");document.getElementById("checkoutListPage").classList.remove("hidden");const s=await db.ref("checkout").once("value");const d=s.val()||{};let ini=[],lama=[];Object.keys(d).forEach(k=>allowedKosts.includes(k)&&Object.keys(d[k]).forEach(r=>{const x=d[k][r];if(x?.tanggalCheckout){const i={room:r,nama:x.nama||"?",durasi:x.durasi||"Bulanan",tgl:x.tanggalCheckout};new Date(x.tanggalCheckout).getMonth()===new Date().getMonth()?ini.push(i):lama.push(i);}}));const r=a=>a.map((x,i)=>`<div class="checkout-item"><strong>${i+1}. ${x.room} - ${x.nama}</strong><br><small>${x.durasi} • ${formatDate(x.tgl)}</small></div>`).join("")||"Kosong";document.getElementById("checkoutBulanIni").innerHTML=r(ini);document.getElementById("checkoutSebelumnya").innerHTML=r(lama);};

window.showCheckinList=async()=>{document.getElementById("app").classList.add("hidden");document.getElementById("checkinListPage").classList.remove("hidden");await loadCheckinList();};
async function loadCheckinList(){const ini=[],lama=[],cm=new Date().getMonth(),cy=new Date().getFullYear();for(const k of allowedKosts)for(const r of kosts[k]){const s=await db.ref(`kosts/${k}/${r}`).once("value");const d=s.val();if(d?.nama&&d.tanggalMasuk){const t=new Date(d.tanggalMasuk);const i={room:r,nama:d.nama,tgl:formatDate(d.tanggalMasuk),durasi:d.durasi||"Bulanan",token:d.tokenAwal||0,status:"Masih Tinggal"};(t.getMonth()===cm&&t.getFullYear()===cy?ini:t.getMonth()===cm-1?lama:null)?.push(i);}}document.getElementById("listCheckinBulanIni").innerHTML=ini.length?ini.map((x,i)=>`<div class="checkout-item"><strong>${i+1}. ${x.room} - ${x.nama}</strong><br><small>${x.tgl} • ${x.durasi} • Token ${x.token} • ${x.status}</small></div>`).join(""):"Belum ada";document.getElementById("listCheckinBulanLalu").innerHTML=lama.length?lama.map((x,i)=>`<div class="checkout-item"><strong>${i+1}. ${x.room} - ${x.nama}</strong><br><small>${x.tgl} • ${x.durasi} • Token ${x.token} • ${x.status}</small></div>`).join(""):"Belum ada";}
window.laporCheckinWA=()=>{loadCheckinList().then(()=>{const ini=Array.from(document.querySelectorAll("#listCheckinBulanIni .checkout-item")).map(e=>e.querySelector("small").textContent);const lama=Array.from(document.querySelectorAll("#listCheckinBulanLalu .checkout-item")).map(e=>e.querySelector("small").textContent);let msg="*LAPORAN CHECK-IN*\n\n*Bulan Ini*: "+ini.length+"\n"+(ini.map((l,i)=>`${i+1}. ${l}`).join("\n")||"Kosong")+"\n\n*Bulan Lalu*: "+lama.length+"\n"+(lama.map((l,i)=>`${i+1}. ${l}`).join("\n")||"Kosong");window.open("https://api.whatsapp.com/send?text="+encodeURIComponent(msg));});};
